name: Relaunch Binary Compilation

on:
  push:
    branches:
    - master
    - release/*
    tags:
      - v*

jobs:
  buildApplet:
    name: Build Relaunch
    container: devkitpro/devkitarm:20200528
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
    - name: Install tools
      run: |
       sudo apt update
       sudo apt install p7zip-full haveged
    - name: make
      run: |
        chmod +x make_cia
        make
        7z a Relaunch.7z Relaunch/
    - name: Commit to Universal-Team/extras
      run: |
        export COMMIT_TAG="$(git log --format=%h -1)"
        export COMMIT_MESSAGE="$(git log --pretty=format:"%an - %s" -1)"
        export CURRENT_DATE="$(date +"%Y%m%d-%H%M%S")"
        echo $COMMIT_TAG > commit.txt
        echo $COMMIT_MESSAGE > message.txt
        echo $CURRENT_DATE > date.txt
        git config --global user.email "flamekat54@aol.com"
        git config --global user.name "TWLBot"
        git clone --depth 1 https://${{ secrets.BOT_TOKEN }}@github.com/Universal-Team/extras.git
        cd extras/builds/Relaunch/
        cp ../../../Relaunch.7z Relaunch.7z
        git stage .
        git commit -m "Relaunch | $COMMIT_TAG"
        git push origin master
    - name: webhook for broke build lmfao
      if: failure() # trash broke, go fix it
      run: |
         COMMIT_TAG=$(<commit.txt)
         COMMIT_MESSAGE=$(<message.txt)
         CURRENT_DATE=$(<date.txt)
         curl -o send.sh https://raw.githubusercontent.com/Universal-Team/discord-webhooks/master/send-ghactions.sh
         sudo chmod +x send.sh
         ./send.sh failure ${{ secrets.WEBHOOK_URL }}
    - name: it work send webhook for success
      if: success() # it worked yay
      run: |
         COMMIT_TAG=$(<commit.txt)
         COMMIT_MESSAGE=$(<message.txt)
         CURRENT_DATE=$(<date.txt)
         curl -o send.sh https://raw.githubusercontent.com/Universal-Team/discord-webhooks/master/send-ghactions.sh
         sudo chmod +x send.sh
         ./send.sh success ${{ secrets.WEBHOOK_URL }}
    - uses: actions/upload-artifact@master
      with:
        name: Relaunch-${{ github.sha }}
        path: Relaunch/
